"""Phase 7: Ship.

After validation shows real improvement, Agent SRE:
  1. Writes a postmortem-style PR document (Markdown) capturing the diagnosis,
     proposed fix, and before/after metrics — judges can read this and verify the
     autonomous reasoning.
  2. Tags the candidate prompt as 'production' in Phoenix (best-effort; falls back
     gracefully if the Phoenix prompt REST endpoint isn't available).

Refuses to ship if the validation delta is non-positive.
"""
from __future__ import annotations

import difflib
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

import httpx

from agent_sre.phases.propose import CandidatePrompt
from agent_sre.phases.synthesize import ClusterDiagnosis
from agent_sre.phases.validate import ValidationResult
from shared import config


@dataclass
class ShipResult:
    shipped: bool
    reason: str
    postmortem_path: str = ""
    postmortem_content: str = ""  # Full markdown text so the dashboard can render inline
    phoenix_response: dict[str, Any] = field(default_factory=dict)


def _prompt_diff(original: str, candidate: str) -> str:
    """Unified diff between the two prompts, rendered for the postmortem."""
    original_lines = original.strip().splitlines(keepends=False)
    candidate_lines = candidate.strip().splitlines(keepends=False)
    diff = difflib.unified_diff(
        original_lines,
        candidate_lines,
        fromfile="prompt (production)",
        tofile="prompt (candidate)",
        lineterm="",
    )
    return "\n".join(diff)


def _write_postmortem(
    candidate: CandidatePrompt,
    diagnoses: list[ClusterDiagnosis],
    validation: ValidationResult,
    original_prompt: str,
    output_dir: str,
) -> tuple[str, str]:
    """Render a Markdown postmortem and write it to disk. Returns (path, content)."""
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = os.path.join(output_dir, f"postmortem-{timestamp}.md")

    lines: list[str] = []
    lines.append(f"# Agent SRE postmortem — {candidate.name}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(timezone.utc).isoformat()}")
    lines.append(f"**Validation score:** {validation.original_score:.0%} → {validation.candidate_score:.0%}  ({validation.delta:+.0%})")
    lines.append(f"**Sample size:** {len(validation.cases)} adversarial cases")
    lines.append("")
    lines.append("## TL;DR")
    lines.append("")
    lines.append(candidate.rationale or "(no rationale captured)")
    lines.append("")
    lines.append("## Failure clusters discovered")
    lines.append("")
    for d in diagnoses:
        lines.append(f"### {d.cluster_label} ({d.severity})")
        lines.append("")
        lines.append(f"**Root cause:** {d.root_cause}")
        lines.append("")
        if d.cited_span_ids:
            lines.append("**Evidence (cited span IDs):**")
            for sid in d.cited_span_ids[:5]:
                lines.append(f"- `{sid}`")
            lines.append("")
        lines.append(f"**Adversarial cases generated:** {len(d.eval_cases)}")
        lines.append("")
    lines.append("## Proposed fix (prompt diff)")
    lines.append("")
    lines.append("```diff")
    lines.append(_prompt_diff(original_prompt, candidate.text))
    lines.append("```")
    lines.append("")
    lines.append("## Validation results")
    lines.append("")
    lines.append("| # | Input | Before | After | Verdict |")
    lines.append("|---|---|---|---|---|")
    for i, c in enumerate(validation.cases, 1):
        before = "PASS" if c.original_passed else "FAIL"
        after = "PASS" if c.candidate_passed else "FAIL"
        verdict = (
            "FIXED" if (not c.original_passed and c.candidate_passed)
            else ("REGRESSED" if (c.original_passed and not c.candidate_passed)
                  else "NO CHANGE")
        )
        input_preview = c.case.input.replace("|", "\\|")[:80]
        lines.append(f"| {i} | {input_preview} | {before} | {after} | {verdict} |")
    lines.append("")
    lines.append("## Auto-generated by Agent SRE")
    lines.append("")
    lines.append("This postmortem was written autonomously by [Agent SRE](https://github.com/) "
                 "after observing production traces in Arize Phoenix, clustering failure modes, "
                 "synthesizing adversarial eval cases, proposing a prompt fix, and validating "
                 "improvement via Phoenix experiments — all without human intervention.")

    content = "\n".join(lines)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path, content


def _tag_as_production(candidate: CandidatePrompt) -> dict[str, Any]:
    """Best-effort: tag the candidate prompt as 'production' in Phoenix.

    The Phoenix REST prompt API has been finicky across versions — if this fails,
    we still consider the ship successful as long as the postmortem was written.
    """
    base_url = config.phoenix_base_url().rstrip("/")
    headers: dict[str, str] = {"Content-Type": "application/json"}
    api_key = config.get("PHOENIX_API_KEY", "")
    if "phoenix.arize.com" in base_url and api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    # Try a simpler payload shape than the previous attempt.
    payload = {
        "name": candidate.name,
        "description": f"Production prompt — Agent SRE applied fix addressing: {', '.join(candidate.addresses_clusters)}",
        "version": {
            "description": candidate.rationale,
            "template": candidate.text,
            "tags": ["production"],
        },
    }
    url = f"{base_url}/v1/prompts"
    with httpx.Client(timeout=30.0) as client:
        r = client.post(url, headers=headers, json=payload)
        r.raise_for_status()
        return r.json()


def ship(
    original_prompt: str,
    candidate: CandidatePrompt,
    diagnoses: list[ClusterDiagnosis],
    validation: ValidationResult,
    output_dir: str = "ship_artifacts",
    min_delta: float = 0.10,
) -> ShipResult:
    """Phase 7: ship the candidate if validation showed real improvement.

    Args:
        original_prompt: the prompt currently in production.
        candidate: the proposed replacement.
        diagnoses: outputs from Phase 3+4 (used to populate the postmortem).
        validation: Phase 6 result.
        output_dir: where to write postmortem markdown.
        min_delta: minimum score improvement required to proceed with ship.

    Returns:
        ShipResult with shipped=True iff the postmortem was written. Phoenix prompt
        push is best-effort.
    """
    if validation.delta < min_delta:
        return ShipResult(
            shipped=False,
            reason=(
                f"validation delta {validation.delta:+.0%} is below minimum threshold "
                f"{min_delta:+.0%}; re-entering loop instead of shipping"
            ),
        )

    pm_path, pm_content = _write_postmortem(
        candidate, diagnoses, validation, original_prompt, output_dir
    )

    # Phoenix prompt tagging is best-effort; we suppress the warning from the
    # dashboard surface so we don't show a half-error half-success status.
    phoenix_response: dict[str, Any] = {}
    try:
        phoenix_response = _tag_as_production(candidate)
    except Exception:
        phoenix_response = {}  # quiet soft-fail

    return ShipResult(
        shipped=True,
        reason=f"delta {validation.delta:+.0%} >= threshold {min_delta:+.0%}",
        postmortem_path=pm_path,
        postmortem_content=pm_content,
        phoenix_response=phoenix_response,
    )
